import { startFakeDGII } from '../support/fake-dgii-server';
import { cleanDatabase, seedDefaultCompany, isSupabaseConfigured } from '../support/test-db';

async function globalSetup() {
  // Start fake DGII server and point the app to it via env
  const url = await startFakeDGII();
  process.env.DGII_URL_BASE = url;

  // Default certificate password for test fixtures (generated by npm run fixtures)
  if (!process.env.CERT_PASSWORD) {
    process.env.CERT_PASSWORD = 'test123';
  }

  if (isSupabaseConfigured()) {
    try {
      await cleanDatabase();
      await seedDefaultCompany();
    } catch (e) {
      // eslint-disable-next-line no-console
      console.warn('Could not seed test database:', String(e));
    }
  } else {
    // eslint-disable-next-line no-console
    console.warn('Supabase env vars missing — skipping seed. E2E specs will skip.');
  }
}

export default globalSetup;
